### PR TITLE
Use run exports from glib to only dependt on libglib at runtime

### PR DESCRIPTION
**Pull request by hmaarrfk**
The dependency on glib  pulls in python and this is not always desirable.

@conda-forge-admin please rerender

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2314#issuecomment-994320154

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
@hmaarrfk in the build with only `libglib` in host, I see things like "2021-12-14T23:59:11.2730618Z checking for GLIB... no" in the log that indicate it wasn't using `glib`. Thus I think the current version is the right one.

**Comment by hmaarrfk** [comment]
Thank you for the thorough review!

**Comment by hmaarrfk** [comment]
@conda-forge/dbus kind ping. Is there anything else that is needed to ensure this package gets the updated dependencies (i.e. the removal of the python dependency).

**Pull request merged**
